# Generated by Django 4.2.13 on 2024-05-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
