
from urllib import response
from django.shortcuts import render, redirect
from proj_app.models import *
from django.contrib.auth import login
from proj_app.forms import ApplicationForm, SupervisorSignUpForm, GroupSignUpForm, Application, Topic, TopicForm
from django.http import HttpResponseRedirect
from django.urls import reverse



# Create your views here.

# def about(request):
#     context={
#         'admin_list': create_admins(),
#     }
#     return render(request, 'proj_app/about.html', context)
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout
from .forms import SupervisorSignUpForm, GroupSignUpForm
from django.contrib.auth.forms import AuthenticationForm
app_name = 'proj_app/'

def register_supervisor(request):
    if request.method == 'POST':
        form = SupervisorSignUpForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')
    else:
        form = SupervisorSignUpForm()
    return render(request, 'proj_app/register_supervisor.html', {'form': form})

def register_group(request):
    if response.method == 'POST':
        form = GroupSignUpForm(response.POST)
        if form.is_valid():
            form.save()
            # return redirect('login')
    else:
        form = GroupSignUpForm()
    return render(request, 'proj_app/register_group.html', {'form': form})

def user_login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('homepage')
    else:
        form = AuthenticationForm()
    return render(request, 'proj_app/login.html', {'form': form})

def user_logout(request):
    logout(request)
    return redirect('login')

def home(request):
    context = {}
    return render(request, app_name + 'home.html', context)

# def add_supervisor(request):

#     page_data = {'myform': SupervisorForm(), }

#     return render(request, app_name + 'add_supervisor.html', page_data)

# def add_supervisor_submit(request):
#     if request.method != 'POST':
#         return HttpResponseRedirect('/add/supervisor/')
#     else:
#         page_data = {}
#         form = SupervisorForm(request.POST)
#         if form.is_valid():
#             save_new_supervisor(form)
#             return HttpResponseRedirect(reverse('homepage'))
#         else:
#             page_data = {'val_errors': form.errors, }

#     return render(request, app_name + 'home.html', page_data)


# def save_new_supervisor(form):
#     #get valid data from form
#     new_sup_object = form.save()

# def modify_supervisor(request, key=1):
#     sup = Supervisor.objects.get(staffID=int(key))

#     page_data = None

#     if request.method == 'POST':
#         if 'edit' in request.POST:
#             print("edit")
#             print(key)
#             form = SupervisorForm(request.POST, instance=sup)
#             page_data = edit_supervisor(form)
#         elif 'delete' in request.POST:
#             page_data = delete_supervisor(sup)
#         return HttpResponseRedirect(reverse('homepage'))
#     else:
#         # This request is not generated by a form's Submit button.
#         # Display the Form containing the queried record.
#         form = SupervisorForm(instance=sup)
#         page_data = {'myform': form,}

#     return render(request, app_name + 'edit_supervisor.html', page_data)

# def edit_supervisor(form):
#     #fetch an existing supervisor record from the database
#     page_data = {}

#     if form.is_valid() != True:
#         # Validation failed. Redisplay the form.
#         page_data = {'myform': form, }
#     else:
#         # Validation passed. Save the data.
#         form.save()

#     return page_data


# def delete_supervisor(sup):
#     sup.delete()
#     return None

# # Views for Groups
# def add_group(request):
#     page_data = {'myform':GroupForm(), }

#     return render(request, app_name + 'add_group.html', page_data)

# def add_group_submit(request):
#     if request.method != 'POST':
#         return HttpResponseRedirect('add_group')
#     else:
#         page_data = {}
#         form = GroupForm(request.POST)
#         if form.is_valid():
#             save_new_group(form)
#             return HttpResponseRedirect(reverse('homepage'))
#         else:
#             page_data = {'val_errors': form.errors, }

#     return render(request, app_name + 'home.html', page_data)

# def modify_group(request, key):
#     grp = Group.objects.get(groupID=int(key))

#     page_data = None

#     if request.method == 'POST':
#         if 'edit' in request.POST:
#             print("edit")
#             print(key)
#             form = GroupForm(request.POST, instance=grp)
#             page_data = edit_group(form)
#         elif 'delete' in request.POST:
#             page_data = delete_group(grp)
#         return HttpResponseRedirect(reverse('homepage'))
#     else:

#         form = GroupForm(instance=grp)
#         page_data = {'myform': form,}

#     return render(request, app_name + 'edit_group.html', page_data)

# def edit_group(form):
#     page_data = {}

#     if form.is_valid() != True:

#         page_data = {'myform': form, }
#     else:

#         form.save()

#     return page_data


# def delete_group(grp):
#     grp.delete()
#     return None

# def save_new_group(form):
#     new_grp_object = form.save()


# Views for Topics
def add_topic(request):
    page_data = {'myform':TopicForm(), }

    return render(request, app_name + 'add_topic.html', page_data)

def add_topic_submit(request):
    if request.method != 'POST':
        return HttpResponseRedirect('add_topic')
    else:
        page_data = {}
        form = TopicForm(request.POST)
        if form.is_valid():
            save_new_topic(form)
            return HttpResponseRedirect(reverse('homepage'))
        else:
            page_data = {'val_errors': form.errors, }

    return render(request, app_name + 'home.html', page_data)

def modify_topic(request, key):
    topic = Topic.objects.get(topicID=int(key))

    page_data = None

    if request.method == 'POST':
        if 'edit' in request.POST:
            print("edit")
            print(key)
            form = TopicForm(request.POST, instance=topic)
            page_data = edit_topic(form)
        elif 'delete' in request.POST:
            page_data = delete_topic(topic)
        return HttpResponseRedirect(reverse('homepage'))
    else:
        form = TopicForm(instance=topic)
        page_data = {'myform': form,}

    return render(request, app_name + 'edit_topic.html', page_data)

def edit_topic(form):
    page_data = {}

    if form.is_valid() != True:
        page_data = {'myform': form, }
    else:
        form.save()

    return page_data


def delete_topic(topic):
    topic.delete()
    return None

def save_new_topic(form):
    new_topic_object = form.save()




# Views for Applications
def add_application(request):
    page_data = {'myform':ApplicationForm(), }

    return render(request, app_name + 'add_application.html', page_data)

def add_application_submit(request):
    if request.method != 'POST':
        return HttpResponseRedirect('add_application')
    else:
        page_data = {}
        form = ApplicationForm(request.POST)
        if form.is_valid():
            save_new_application(form)
            return HttpResponseRedirect(reverse('homepage'))
        else:
            page_data = {'val_errors': form.errors, }

    return render(request, app_name + 'home.html', page_data)

def modify_application(request, key):
    app = Application.objects.get(id=int(key))

    page_data = None

    if request.method == 'POST':
        if 'edit' in request.POST:
            print("edit")
            print(key)
            form = ApplicationForm(request.POST, instance=app)
            page_data = edit_application(form)
        elif 'delete' in request.POST:
            page_data = delete_application(app)
        return HttpResponseRedirect(reverse('homepage'))
    else:
        form = ApplicationForm(instance=app)
        page_data = {'myform': form,}

    return render(request, app_name + 'edit_application.html', page_data)

def edit_application(form):
    page_data = {}

    if form.is_valid() != True:
        page_data = {'myform': form, }
    else:
        form.save()

    return page_data


def delete_application(app):
    app.delete()
    return None

def save_new_application(form):
    new_application_object = form.save()


# def delete_supervisor(request, key):
#     sup = Supervisor.objects.get(id=int(key))

#     if request.method == 'POST':
#         form = SupervisorForm(request.POST, instance=sup)
#         sup.delete()
#         return HttpResponseRedirect(reverse('homepage'))
    
#     else: #GET request from entering url

#         form = SupervisorForm(instance=sup)
#         page_data = {
#             'myform': form,
#         }

#     return render(request, app_name + 'delete_supervisor.html', page_data)







# def proj_list(request):
#     context={
#         'proj_list': create_topics(),
#     }
#     return render(request, 'proj_app/project_list.html', context)

# def project_details(request, topic_id):
#     # Retrieve the project with the given ID
#     projects = create_topics()
#     project = None
#     for proj in projects:
#         if proj.id == topic_id:
#             project = proj
#             break

#     context = {
#         'project': project
#     }
#     return render(request, 'proj_app/project_details.html', context)

# def create_admins():
#     admin_list=[]

#     admin_list.append(Admin(361066,
#                             'Moiz Ali'))
#     admin_list.append(Admin(361222,
#                             'Muhammed Abed'))
#     admin_list.append(Admin(365145,
#                             'Heshara Danathma Balasooriya Balasooriya Mudiyanselage'))
#     admin_list.append(Admin(365635,
#                             'Gokul Ashok'))      
#     return admin_list


# # Define Admin class
# class Admin:
#     def __init__(self, id, name):
#         self.id = id
#         self.name= name

    
#     def __str__(self):
#         return str(self.id) +", " + self.name


# # Define Topic Class
# class Topic():
#     def __init__(self, id, title, catg, description, brief_description, supervisor, cas, syd, ext, chem, civil,
#                  eee, mech, cs, cyber, datasc, infosys, seng):
#         self.id = id
#         self.title = title
#         self.catg = catg
#         self.description = description
#         self.brief_description = brief_description
#         self.supervisor = supervisor
#         self.cas = cas
#         self.syd = syd
#         self.ext = ext
#         self.chem = chem
#         self.civil = civil
#         self.eee = eee
#         self.mech = mech
#         self.cs = cs
#         self.cyber = cyber
#         self.datasc = datasc
#         self.infosys = infosys
#         self.seng = seng

#         def __str__(self):
#             return self.title
      
# def create_topics():
#     topic_list=[]

#     topic_list.append(Topic(1,
#                             'Machine learning approaches for Cyber Security ',
#                             'Artificial Intelligence, Machine Learning and Data Science',
#                             'As we use internet more, the data produced by us is enormous. But are these data being secure? The goal of applying machine learning or intelligence is to better risk modelling and prediction and for an informed decision support. Students will be working with either supervised or unsupervised machine learning approaches to solve the problem/s in the broader areas of Cyber Security.',
#                             'Internet usage generates vast amounts of data, raising security concerns. Machine learning aims to enhance risk modeling and prediction for informed decision-making in cybersecurity, employing supervised or unsupervised methods for student projects.',
#                             'Bharanidharan Shanmugam',
#                             True,
#                             True,
#                             True,
#                             False,
#                             False,
#                             False,
#                             False,
#                             True,
#                             False,
#                             False,
#                             True,
#                             True))
#     topic_list.append(Topic(9,
#                             'Informetrics applications in multidisciplinary domain',
#                             'Artificial Intelligence, Machine Learning and Data Science',
#                             'Informetrics studies are concerned with the quantitative aspects of information. The applications of advanced machine learning, information retrieval, network science and bibliometric techniques on various information artefact have contributed fresh insights into the evolutionary nature of research fields. This project aims at discovering informetric properties of multidisciplinary research literature using various machine learning, network analysis, data visualisation and data wrangling tools.',
#                             'Informetrics explores quantitative aspects of information. Combining advanced machine learning, information retrieval, and network science, this project delves into multidisciplinary research literature to uncover informetric properties using data analysis and visualization tools.',
#                             'Yakub Sebastian',
#                             True,
#                             True,
#                             True,
#                             False,
#                             False,
#                             False,
#                             False,
#                             True,
#                             True,
#                             True,
#                             True,
#                             True))
#     topic_list.append(Topic(16,
#                             'Development of a Virtual Reality System to Test Binaural Hearing',
#                             'Biomedical Engineering and Health Informatics',
#                             'A virtual reality system could be used to objectively test the binaural hearing ability of humans (the ability to hear stereo and locate the direction and distance of sound). This project aims to design, implement and evaluate a VR system using standard off the shelf components (VR goggle and headphones) and standard programming techniques.',
#                             'This project develops a VR system to objectively test human binaural hearing abilities, enabling sound localization assessments using standard VR components and programming methods.',
#                             'Sami Azam',
#                             True,
#                             False,
#                             True,
#                             False,
#                             False,
#                             True,
#                             False,
#                             True,
#                             False,
#                             False,
#                             False,
#                             True))
#     topic_list.append(Topic(41,
#                             'Current trends on cryptomining and its potential impact on cryptocurrencies',
#                             'Cyber Security',
#                             """Cryptomining is the process of mining crypto currencies by running a sequence of algorithms. Traditionally, to mine new crypto coins, a person (or group of people) would buy expensive computers and spend a lot of time and money running them to perform the difficult calculations to generate crypto coins. Some website owners have started taking a different approach; they have put the software which runs those difficult calculations into their website's Javascript. This then causes the computers belonging to the visitors of their website to run those calculations for them, instead of running them themselves. In other words, when you visit a website with an embedded crypto-miner in it, your computer and electricity is used to try to generate crypto-coins for the owners of that website. Although there are various measures being applied to stop these illegitimate minings, the trend is still increasing. This research aims to find out potential gaps in current methodologies and develop a solution that can fulfil the gap. It also aims to find out:
#                             •	What type crypto mining methodologies are being applied?
#                             •	Apart from crypto-mining, what other security risks may it introduce? For example: cryptojacking
#                             •	How current web standards are tackling this problem?""",
#                             "Cryptomining involves running algorithms to mine cryptocurrencies. Some websites embed crypto-mining scripts in their JavaScript, exploiting visitors' CPUs. This research seeks to address gaps in current methodologies and explore associated security risks like cryptojacking.",
#                             'Sami Azam',
#                             True,
#                             True,
#                             True,
#                             False,
#                             False,
#                             False,
#                             False,
#                             True,
#                             True,
#                             False,
#                             False,
#                             True))
    
#     topic_list.append(Topic(176,
#                             'Artificial Intelligence in Health Informatics',
#                             'Artificial Intelligence, Machine Learning and Data Science',
#                             'The project aims to use multiple publicly available health datasets to formulate a different dataset that may have features from the original set along with new ones developed through feature engineering. The dataset will then be used to build predictive model based on both general and deep learning based algorithm. The findings will be analysed and compared to similar research works.',
#                             'This project aims to merge public health datasets, enhancing them through feature engineering. A predictive model will be developed using both traditional and deep learning algorithms, with results analyzed and compared to existing research.',
#                             'Asif Karim',
#                             True,
#                             True,
#                             True,
#                             False,
#                             False,
#                             True,
#                             False,
#                             True,
#                             False,
#                             True,
#                             False,
#                             True))
    
#     topic_list.append(Topic(180,
#                             'Unsupervised Model Development from Autism Screening Data ',
#                             'Artificial Intelligence, Machine Learning and Data Science',
#                             'The proposed system will present a two-cluster solution from a given dataset which will group toddlers based on multiple common medical traits. In depth literature survey of similar studies, both supervised and unsupervised will be carried out before the cluster-based model is implemented. The solution will be validated using both External and Internal validation measures and statistical significance tests.',
#                             'This system will cluster toddlers based on medical traits from a dataset. A comprehensive literature review on similar studies will precede the implementation of a cluster-based model. Validation will utilize external/internal measures and statistical tests.',
#                             'Asif Karim',
#                             True,
#                             True,
#                             True,
#                             False,
#                             False,
#                             True,
#                             False,
#                             True,
#                             False,
#                             True,
#                             False,
#                             True))
    
#     topic_list.append(Topic(226,
#                             'Applying Artificial Intelligence to solve real world problems ',
#                             'Artificial Intelligence, Machine Learning and Data Science',
#                             'Artificial Intelligence has been used in many applications to solve certain problems through out the academia and the industry – from electricity to writing text. AI has a multitude of applications and this project will pick up a problem and explore the applications of AI with minimal human intervention. Examples of applications include -building a bot, predicting the power usage, spam filtering and the list is endless.',
#                             'AI is widely applied across academia and industry, tackling diverse challenges from electricity to text generation. This project selects a specific problem and investigates AI applications with minimal human involvement, such as building bots, power usage prediction, and spam filtering.',
#                             'Bharanidharan Shanmugam',
#                             True,
#                             True,
#                             True,
#                             True,
#                             True,
#                             True,
#                             True,
#                             True,
#                             True,
#                             True,
#                             True,
#                             True))
#     print (topic_list)
      
#     return topic_list